/**
 * Categories Collection Definition
 *
 * Collection: categories
 * Purpose: Product and content categorization (Comida, Ropa, Tecnología, etc.)
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   name: string,                  // Category name (e.g., "Comida", "Ropa")
 *   slug: string,                  // URL-friendly name (e.g., "comida", "ropa")
 *   icon: string,                  // Ionicon name for category
 *   color: string,                 // Hex color for category theme
 *   description: string,           // Category description
 *   parentId: string,              // Reference to parent category (for subcategories)
 *   order: number,                 // Display order
 *   isActive: boolean,             // Whether category is active
 *   metadata: {
 *     productCount: number,        // Number of products in category
 *     businessCount: number,       // Number of businesses in category
 *   },
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - isActive + order (category listing)
 * - slug (category lookup)
 * - parentId + order (subcategories)
 */

export const COLLECTION_NAME = 'categories';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  name: 'string (required, max 50)',
  slug: 'string (required, unique, lowercase)',
  icon: 'string (required, Ionicon name)',
  color: 'string (required, hex color)',
  description: 'string (optional, max 200)',
  parentId: 'string (optional, null for top-level)',
  order: 'number (required, for sorting)',
  isActive: 'boolean (default true)',
  metadata: 'object (optional)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const FIRESTORE_RULES = `
  // Categories - Read only for all authenticated users
  match /categories/{categoryId} {
    allow read: if request.auth != null;
    allow write: if request.auth != null
      && get(/databases/$(database)/documents/users/$(request.auth.uid)).data.userType == 'admin';
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'categories',
    fields: [
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'order', order: 'ASCENDING' }
    ]
  },
  {
    collection: 'categories',
    fields: [
      { fieldPath: 'parentId', order: 'ASCENDING' },
      { fieldPath: 'order', order: 'ASCENDING' }
    ]
  }
];
