/**
 * Venezuelan States Collection Definition
 *
 * Collection: venezuelan_states
 * Purpose: Catalog of Venezuelan states for address selection
 *
 * Document Structure:
 * {
 *   id: string,           // Document ID, same as code (e.g., "ZUL")
 *   name: string,         // Full state name (e.g., "Zulia")
 *   code: string,         // State code (e.g., "ZUL")
 *   createdAt: Timestamp, // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp  // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - name (for alphabetical ordering)
 * - code (for code lookups)
 *
 * Security Rules:
 * - Read: Authenticated users only
 * - Write: Admin only (via backend)
 */

export const COLLECTION_NAME = 'venezuelan_states';

export const COLLECTION_SCHEMA = {
  id: 'string (required)',
  name: 'string (required, max 100)',
  code: 'string (required, max 10, uppercase)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const FIRESTORE_RULES = `
  // Venezuelan States - Read only for authenticated users
  match /venezuelan_states/{stateId} {
    allow read: if request.auth != null;
    allow write: if false; // Admin only via backend
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'venezuelan_states',
    fields: [
      { fieldPath: 'name', order: 'ASCENDING' }
    ]
  },
  {
    collection: 'venezuelan_states',
    fields: [
      { fieldPath: 'code', order: 'ASCENDING' }
    ]
  }
];