/**
 * Favorites Collection Definition
 *
 * Collection: favorites
 * Purpose: User saved items (products, posts, videos)
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   userId: string,                // Reference to users collection
 *
 *   // Saved Item Reference
 *   itemType: string,              // 'product' | 'post'
 *   itemId: string,                // Reference to product or post
 *
 *   // Metadata (denormalized for quick access)
 *   metadata: object,              // Cached item data
 *   // Example for product: { name: '...', thumbnailUrl: '...', price: 10 }
 *   // Example for post: { caption: '...', thumbnailUrl: '...', businessId: '...' }
 *
 *   // Timestamps
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - userId + itemType + createdAt (user favorites by type)
 * - userId + itemId (check if item is favorited)
 */

export const COLLECTION_NAME = 'favorites';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  userId: 'string (required)',
  itemType: 'string (required, product|post)',
  itemId: 'string (required)',
  metadata: 'object (optional, cached data)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const FAVORITE_TYPES = {
  PRODUCT: 'product',
  POST: 'post'
};

export const FIRESTORE_RULES = `
  // Favorites - Users can only access their own favorites
  match /favorites/{favoriteId} {
    allow read, write: if request.auth != null
      && request.auth.uid == resource.data.userId;
    allow create: if request.auth != null
      && request.auth.uid == request.resource.data.userId;
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'favorites',
    fields: [
      { fieldPath: 'userId', order: 'ASCENDING' },
      { fieldPath: 'itemType', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'favorites',
    fields: [
      { fieldPath: 'userId', order: 'ASCENDING' },
      { fieldPath: 'itemId', order: 'ASCENDING' }
    ]
  }
];
