/**
 * Addresses Collection Definition
 *
 * Collection: addresses
 * Purpose: User addresses with relationships to address types and states
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   userId: string,                // Reference to users collection
 *   addressTypeId: string,         // Reference to address_types collection
 *
 *   // Basic Info
 *   label: string,                 // User-defined label (e.g., "Casa", "Oficina principal")
 *   contactName: string,           // Contact person name
 *   phone: string,                 // Contact phone (Venezuelan format)
 *
 *   // Address Details
 *   street: string,                // Complete street address
 *   city: string,                  // City name
 *   stateId: string,               // Reference to venezuelan_states collection
 *   postalCode: string,            // Postal code (4-5 digits)
 *   references: string,            // Delivery references
 *
 *
 *   // Geolocation
 *   coordinates: {
 *     latitude: number,            // Latitude (-90 to 90)
 *     longitude: number,           // Longitude (-180 to 180)
 *     latitudeDelta: number,       // Map zoom level (north-south)
 *     longitudeDelta: number,      // Map zoom level (east-west)
 *     accuracyMeters: number       // GPS accuracy (optional)
 *   },
 *
 *   // Metadata
 *   userTypeId: string,            // Reference to user_types collection (client, business, driver)
 *   isDefault: boolean,            // Is this the default address
 *   isActive: boolean,             // Soft delete flag
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - userId + isActive + createdAt (user addresses)
 * - userId + isDefault (default address)
 * - userId + addressTypeId + isActive (addresses by type)
 *
 * Security Rules:
 * - Read/Write: Users can only access their own addresses
 */

export const COLLECTION_NAME = 'addresses';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  userId: 'string (required)',
  addressTypeId: 'string (required)',
  label: 'string (required, max 50)',
  contactName: 'string (required, max 100)',
  phone: 'string (required, Venezuelan format)',
  street: 'string (required, max 200)',
  city: 'string (required, max 100)',
  stateId: 'string (required)',
  postalCode: 'string (required, 4-5 digits)',
  references: 'string (required, max 300)',
  coordinates: 'object (required)',
  userTypeId: 'string (required, client|business|driver)',
  isDefault: 'boolean (default false)',
  isActive: 'boolean (default true)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const FIRESTORE_RULES = `
  // Addresses - Users can only access their own addresses
  match /addresses/{addressId} {
    allow read, write: if request.auth != null
      && request.auth.uid == resource.data.userId;
    allow create: if request.auth != null
      && request.auth.uid == request.resource.data.userId;
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'addresses',
    fields: [
      { fieldPath: 'userId', order: 'ASCENDING' },
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'addresses',
    fields: [
      { fieldPath: 'userId', order: 'ASCENDING' },
      { fieldPath: 'isDefault', order: 'ASCENDING' }
    ]
  },
  {
    collection: 'addresses',
    fields: [
      { fieldPath: 'userId', order: 'ASCENDING' },
      { fieldPath: 'addressTypeId', order: 'ASCENDING' },
      { fieldPath: 'isActive', order: 'ASCENDING' }
    ]
  }
];