/**
 * User Types Collection Definition
 *
 * Collection: user_types
 * Purpose: Reference table for user types (client, business, driver)
 *
 * Document Structure:
 * {
 *   id: string,                    // USER_TYPE_ID (CLIENT, BUSINESS, DRIVER)
 *   name: string,                  // Display name (Cliente, Negocio, Repartidor)
 *   description: string,           // Description of user type
 *   permissions: array,            // Array of permission strings
 *   isActive: boolean,             // Whether this user type is active
 *   features: object,              // Feature flags specific to this user type
 *   addressBehavior: object,       // How addresses work for this user type
 *   uiConfig: object,             // UI configuration for this user type
 *   createdAt: Timestamp,         // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp          // Auto-generated by BaseFirebaseService
 * }
 */

export const COLLECTION_NAME = 'user_types';

export const COLLECTION_SCHEMA = {
  id: 'string (predefined: CLIENT|BUSINESS|DRIVER)',
  name: 'string (required, max 50)',
  description: 'string (required, max 200)',
  permissions: 'array (required)',
  isActive: 'boolean (default true)',
  features: 'object (optional)',
  addressBehavior: 'object (required)',
  uiConfig: 'object (required)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const USER_TYPES = {
  CLIENT: 'CLIENT',
  BUSINESS: 'BUSINESS',
  DRIVER: 'DRIVER'
};

export const FIRESTORE_RULES = `
  // User Types - Read only for authenticated users
  match /user_types/{userTypeId} {
    allow read: if request.auth != null;
  }
`;