/**
 * Stories Collection Definition
 *
 * Collection: stories
 * Purpose: Temporary social content (24-hour expiration like Instagram Stories)
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   businessId: string,            // Reference to businesses collection
 *   userId: string,                // Reference to users collection (creator)
 *
 *   // Content
 *   type: string,                  // 'image' | 'video'
 *   mediaUrl: string,              // Media URL (image or video)
 *   thumbnailUrl: string,          // Thumbnail for video
 *   duration: number,              // Display duration in seconds (default 5 for images, video length for videos)
 *
 *   // Interactive Elements
 *   taggedProducts: array,         // Array of product IDs tagged in story
 *   stickers: array,               // Stickers, text, polls, etc.
 *   // Example: [{ type: 'text', content: '¡Oferta!', position: {...} }]
 *   link: object,                  // Swipe-up link
 *   // Example: { url: '/products/123', text: 'Ver Producto' }
 *
 *   // Status
 *   isActive: boolean,             // Whether story is active
 *   isExpired: boolean,            // Whether story has expired
 *
 *   // Engagement Metrics
 *   viewCount: number,             // Number of views
 *   replyCount: number,            // Number of replies
 *   shareCount: number,            // Number of shares
 *   tapForwardCount: number,       // Number of forward taps
 *   tapBackCount: number,          // Number of back taps
 *   exitCount: number,             // Number of exits
 *
 *   // Timestamps
 *   expiresAt: Timestamp,          // When story expires (24h from creation)
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - businessId + isActive + expiresAt (business stories)
 * - isActive + expiresAt (cleanup query)
 */

export const COLLECTION_NAME = 'stories';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  businessId: 'string (required)',
  userId: 'string (required)',
  type: 'string (required, image|video)',
  mediaUrl: 'string (required)',
  thumbnailUrl: 'string (required for videos)',
  duration: 'number (default 5)',
  taggedProducts: 'array (optional)',
  stickers: 'array (optional)',
  link: 'object (optional)',
  isActive: 'boolean (default true)',
  isExpired: 'boolean (default false)',
  viewCount: 'number (default 0)',
  replyCount: 'number (default 0)',
  shareCount: 'number (default 0)',
  tapForwardCount: 'number (default 0)',
  tapBackCount: 'number (default 0)',
  exitCount: 'number (default 0)',
  expiresAt: 'Timestamp (auto, 24h from creation)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const STORY_TYPES = {
  IMAGE: 'image',
  VIDEO: 'video'
};

export const STORY_DURATION = {
  DEFAULT_IMAGE: 5,    // 5 seconds for images
  MAX_VIDEO: 60        // 60 seconds max for videos
};

export const STORY_EXPIRATION_HOURS = 24;

export const FIRESTORE_RULES = `
  // Stories - Read by all, write by business owner
  match /stories/{storyId} {
    allow read: if request.auth != null
      && resource.data.isActive == true
      && resource.data.expiresAt > request.time;
    allow create: if request.auth != null
      && request.resource.data.businessId in get(/databases/$(database)/documents/users/$(request.auth.uid)).data.businesses;
    allow update, delete: if request.auth != null
      && resource.data.businessId in get(/databases/$(database)/documents/users/$(request.auth.uid)).data.businesses;
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'stories',
    fields: [
      { fieldPath: 'businessId', order: 'ASCENDING' },
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'expiresAt', order: 'ASCENDING' }
    ]
  },
  {
    collection: 'stories',
    fields: [
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'expiresAt', order: 'ASCENDING' }
    ]
  }
];
