/**
 * Products Collection Definition
 *
 * Collection: products
 * Purpose: Business products/services catalog
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   businessId: string,            // Reference to businesses collection
 *   categoryId: string,            // Reference to categories collection
 *
 *   // Basic Info
 *   name: string,                  // Product name
 *   description: string,           // Product description
 *   price: number,                 // Price in currency
 *   compareAtPrice: number,        // Original price (for discounts)
 *   currency: string,              // Currency code (USD, VES, etc.)
 *
 *   // Media
 *   images: array,                 // Array of image URLs
 *   videos: array,                 // Array of video URLs
 *   thumbnailUrl: string,          // Main thumbnail image
 *
 *   // Inventory
 *   stock: number,                 // Available quantity
 *   sku: string,                   // Stock keeping unit
 *   trackInventory: boolean,       // Whether to track inventory
 *
 *   // Variants
 *   hasVariants: boolean,          // Whether product has variants
 *   variants: array,               // Variant options (size, color, etc.)
 *   // Example: [{ name: 'Talla', options: ['S', 'M', 'L'] }]
 *
 *   // Specifications
 *   specifications: object,        // Custom specifications
 *   // Example: { weight: '500g', material: 'Cotton' }
 *
 *   // Food-specific (if category is food)
 *   allergens: array,              // Allergen information
 *   ingredients: array,            // List of ingredients
 *
 *   // Status & Visibility
 *   isActive: boolean,             // Whether product is active
 *   isAvailable: boolean,          // Whether currently available
 *   isFeatured: boolean,           // Featured product
 *
 *   // Metrics
 *   viewCount: number,             // Number of views
 *   favoriteCount: number,         // Number of favorites
 *   orderCount: number,            // Number of orders
 *   rating: number,                // Average rating (0-5)
 *   reviewCount: number,           // Number of reviews
 *
 *   // Timestamps
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - businessId + isActive + createdAt (business products)
 * - categoryId + isActive + createdAt (category products)
 * - isActive + isFeatured + createdAt (featured products)
 */

export const COLLECTION_NAME = 'products';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  businessId: 'string (required)',
  categoryId: 'string (required)',
  name: 'string (required, max 100)',
  description: 'string (required, max 1000)',
  price: 'number (required, min 0)',
  compareAtPrice: 'number (optional)',
  currency: 'string (default USD)',
  images: 'array (optional)',
  videos: 'array (optional)',
  thumbnailUrl: 'string (optional)',
  stock: 'number (default 0)',
  sku: 'string (optional)',
  trackInventory: 'boolean (default true)',
  hasVariants: 'boolean (default false)',
  variants: 'array (optional)',
  specifications: 'object (optional)',
  allergens: 'array (optional)',
  ingredients: 'array (optional)',
  isActive: 'boolean (default true)',
  isAvailable: 'boolean (default true)',
  isFeatured: 'boolean (default false)',
  viewCount: 'number (default 0)',
  favoriteCount: 'number (default 0)',
  orderCount: 'number (default 0)',
  rating: 'number (default 0)',
  reviewCount: 'number (default 0)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const PRODUCT_STATUS = {
  ACTIVE: 'active',
  DRAFT: 'draft',
  ARCHIVED: 'archived'
};

export const FIRESTORE_RULES = `
  // Products - Read by all, write by business owner
  match /products/{productId} {
    allow read: if request.auth != null;
    allow create: if request.auth != null
      && request.resource.data.businessId in get(/databases/$(database)/documents/users/$(request.auth.uid)).data.businesses;
    allow update, delete: if request.auth != null
      && resource.data.businessId in get(/databases/$(database)/documents/users/$(request.auth.uid)).data.businesses;
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'products',
    fields: [
      { fieldPath: 'businessId', order: 'ASCENDING' },
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'products',
    fields: [
      { fieldPath: 'categoryId', order: 'ASCENDING' },
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'products',
    fields: [
      { fieldPath: 'isActive', order: 'ASCENDING' },
      { fieldPath: 'isFeatured', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  }
];
