/**
 * Follows Collection Definition
 *
 * Collection: follows
 * Purpose: User following relationships (users following businesses)
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   followerId: string,            // User who is following (reference to users)
 *   followingId: string,           // Business being followed (reference to businesses)
 *   followingType: string,         // Type: 'business' (can extend to 'user' later)
 *
 *   // Notification Preferences
 *   notifyOnNewPost: boolean,      // Notify on new posts
 *   notifyOnNewProduct: boolean,   // Notify on new products
 *   notifyOnStory: boolean,        // Notify on new stories
 *
 *   // Timestamps
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - followerId + createdAt (user's following list)
 * - followingId + createdAt (business's followers)
 * - followerId + followingId (check if following)
 */

export const COLLECTION_NAME = 'follows';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  followerId: 'string (required)',
  followingId: 'string (required)',
  followingType: 'string (required, business)',
  notifyOnNewPost: 'boolean (default true)',
  notifyOnNewProduct: 'boolean (default false)',
  notifyOnStory: 'boolean (default true)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const FOLLOWING_TYPES = {
  BUSINESS: 'business'
  // Future: USER: 'user'
};

export const FIRESTORE_RULES = `
  // Follows - Users can only manage their own follows
  match /follows/{followId} {
    allow read: if request.auth != null;
    allow create: if request.auth != null
      && request.auth.uid == request.resource.data.followerId;
    allow update, delete: if request.auth != null
      && request.auth.uid == resource.data.followerId;
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'follows',
    fields: [
      { fieldPath: 'followerId', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'follows',
    fields: [
      { fieldPath: 'followingId', order: 'ASCENDING' },
      { fieldPath: 'createdAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'follows',
    fields: [
      { fieldPath: 'followerId', order: 'ASCENDING' },
      { fieldPath: 'followingId', order: 'ASCENDING' }
    ]
  }
];
