/**
 * Address Types Collection Definition
 *
 * Collection: address_types
 * Purpose: Catalog of address types available for different user types
 *
 * Document Structure:
 * {
 *   id: string,                    // Document ID (e.g., "CLIENT_HOME")
 *   name: string,                  // Display name (e.g., "Casa")
 *   description: string,           // Description of the address type
 *   allowedForUserTypes: string[], // Array of user types ["client", "business", "driver"]
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - allowedForUserTypes (array-contains queries)
 *
 * Security Rules:
 * - Read: Authenticated users only
 * - Write: Admin only (via backend)
 */

export const COLLECTION_NAME = 'address_types';

export const COLLECTION_SCHEMA = {
  id: 'string (required)',
  name: 'string (required, max 100)',
  description: 'string (optional, max 300)',
  allowedForUserTypes: 'array<string> (required)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const FIRESTORE_RULES = `
  // Address Types - Read only for authenticated users
  match /address_types/{typeId} {
    allow read: if request.auth != null;
    allow write: if false; // Admin only via backend
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'address_types',
    fields: [
      { fieldPath: 'allowedForUserTypes', order: 'ARRAY' }
    ]
  }
];