/**
 * Posts Collection Definition
 *
 * Collection: posts
 * Purpose: Social media posts (photos/videos) with tagged products
 *
 * Document Structure:
 * {
 *   id: string,                    // Auto-generated document ID
 *   businessId: string,            // Reference to businesses collection
 *   userId: string,                // Reference to users collection (creator)
 *
 *   // Content
 *   type: string,                  // 'image' | 'video' | 'carousel'
 *   caption: string,               // Post caption/description
 *   media: array,                  // Media URLs (images or videos)
 *   // Example: [{ type: 'image', url: '...', thumbnailUrl: '...' }]
 *   thumbnailUrl: string,          // Main thumbnail
 *
 *   // Tagged Products
 *   taggedProducts: array,         // Array of tagged product objects with position data
 *   // Example: [{ productId: 'abc123', position: { x: 0.5, y: 0.5 }, mediaIndex: 0 }]
 *   // API populates with full product: [{ productId, position, mediaIndex, product: {...} }]
 *
 *   // Metadata
 *   hashtags: array,               // Array of hashtags
 *   mentions: array,               // Array of mentioned user IDs
 *   location: object,              // Location data
 *   // Example: { name: 'Caracas', coordinates: {...} }
 *
 *   // Status & Visibility
 *   isActive: boolean,             // Whether post is active
 *   isPublished: boolean,          // Whether post is published (or draft)
 *   isPinned: boolean,             // Pinned to profile
 *
 *   // Engagement Metrics
 *   likeCount: number,             // Number of likes
 *   commentCount: number,          // Number of comments
 *   shareCount: number,            // Number of shares
 *   viewCount: number,             // Number of views (for videos)
 *   saveCount: number,             // Number of saves
 *
 *   // Timestamps
 *   publishedAt: Timestamp,        // When post was published
 *   createdAt: Timestamp,          // Auto-generated by BaseFirebaseService
 *   updatedAt: Timestamp           // Auto-generated by BaseFirebaseService
 * }
 *
 * Indexes Required:
 * - businessId + isPublished + publishedAt (business posts feed)
 * - isPublished + publishedAt (global feed)
 * - userId + isPublished + publishedAt (user posts)
 */

export const COLLECTION_NAME = 'posts';

export const COLLECTION_SCHEMA = {
  id: 'string (auto-generated)',
  businessId: 'string (required)',
  userId: 'string (required)',
  type: 'string (required, image|video|carousel)',
  caption: 'string (optional, max 2200)',
  media: 'array (required, min 1)',
  thumbnailUrl: 'string (required)',
  taggedProducts: 'array (optional)',
  hashtags: 'array (optional)',
  mentions: 'array (optional)',
  location: 'object (optional)',
  isActive: 'boolean (default true)',
  isPublished: 'boolean (default true)',
  isPinned: 'boolean (default false)',
  likeCount: 'number (default 0)',
  commentCount: 'number (default 0)',
  shareCount: 'number (default 0)',
  viewCount: 'number (default 0)',
  saveCount: 'number (default 0)',
  publishedAt: 'Timestamp (auto)',
  createdAt: 'Timestamp (auto)',
  updatedAt: 'Timestamp (auto)'
};

export const POST_TYPES = {
  IMAGE: 'image',
  VIDEO: 'video',
  CAROUSEL: 'carousel'
};

export const FIRESTORE_RULES = `
  // Posts - Read by all, write by business owner
  match /posts/{postId} {
    allow read: if request.auth != null && resource.data.isPublished == true;
    allow create: if request.auth != null
      && request.resource.data.businessId in get(/databases/$(database)/documents/users/$(request.auth.uid)).data.businesses;
    allow update, delete: if request.auth != null
      && resource.data.businessId in get(/databases/$(database)/documents/users/$(request.auth.uid)).data.businesses;
  }
`;

export const REQUIRED_INDEXES = [
  {
    collection: 'posts',
    fields: [
      { fieldPath: 'businessId', order: 'ASCENDING' },
      { fieldPath: 'isPublished', order: 'ASCENDING' },
      { fieldPath: 'publishedAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'posts',
    fields: [
      { fieldPath: 'isPublished', order: 'ASCENDING' },
      { fieldPath: 'publishedAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'posts',
    fields: [
      { fieldPath: 'userId', order: 'ASCENDING' },
      { fieldPath: 'isPublished', order: 'ASCENDING' },
      { fieldPath: 'publishedAt', order: 'DESCENDING' }
    ]
  },
  {
    collection: 'posts',
    fields: [
      { fieldPath: 'type', order: 'ASCENDING' },
      { fieldPath: 'isPublished', order: 'ASCENDING' },
      { fieldPath: 'publishedAt', order: 'DESCENDING' }
    ]
  }
];
